#!/usr/bin/env bash
#
# Writes, into YOUR DSH home patch layer, the absolute paths that the bundle
# `dsh-on-fire` cannot guess.
#
# Why this exists: the bundle ships `command: graphify-mcp` and `command: npx`, which are
# portable but depend on PATH. The DSH host PATH is usually minimal and may not
# contain `~/.local/bin` nor the mise shims — and then the MCP server does not come up. Since the
# bundle uses `failOnStartupError: false`, it would fail silently.
#
# This script detects the real paths of this machine and writes an override by id in
# the user layer, which is applied AFTER the bundle and therefore wins.
#
# Reminder: a patch by id replaces the ENTIRE `config` of the row, it does not merge. That is why
# the blocks below repeat the full content, instead of changing only the `command`.
#
# It is idempotent: running it again replaces the managed block and does not touch the rest of the file.
#
# Usage:  ./install/adjust-paths.sh
#
set -euo pipefail

DSH_HOME_DIR="${DSH_HOME:-$HOME/.dsh}"
PATCH="$DSH_HOME_DIR/cordis.patch.yml"
START="# >>> dsh-on-fire: machine paths (generated by install/adjust-paths.sh)"
END="# <<< dsh-on-fire: end"

# ── detection ─────────────────────────────────────────────────────────────────
# We prefer the STABLE paths: `~/.local/bin/graphify-mcp` is a symlink that uv
# keeps pointing at the installed version, and the mise shim survives node
# upgrades. A versioned path (…/installs/node/26.8.1/bin/npx) breaks on the next upgrade.
detect_stable() {
	local preferred="$1" variable="$2"
	if [ -n "${!variable:-}" ]; then
		printf '%s' "${!variable}"
	elif [ -x "$preferred" ]; then
		printf '%s' "$preferred"
	else
		command -v "$(basename "$preferred")" 2>/dev/null || true
	fi
}

GRAPHIFY_MCP="$(detect_stable "$HOME/.local/bin/graphify-mcp" GRAPHIFY_MCP)"
NPX_BIN="$(detect_stable "$HOME/.local/share/mise/shims/npx" NPX_BIN)"

if [ -z "$GRAPHIFY_MCP" ]; then
	echo "warning: 'graphify-mcp' is not on PATH — the graphify row keeps the bundle default." >&2
fi
if [ -z "$NPX_BIN" ]; then
	echo "warning: 'npx' is not on PATH — the lgpd row keeps the bundle default." >&2
fi

if [ ! -f "$PATCH" ]; then
	mkdir -p "$DSH_HOME_DIR"
	printf '%s\n' \
		"# User patch layer (DSH home), applied AFTER every profile layer." \
		"# The managed block at the end comes from dsh-on-fire/install/adjust-paths.sh." \
		>"$PATCH"
fi

# backup before touching it
cp "$PATCH" "$PATCH.bak-$(date +%Y%m%d-%H%M%S)"

# ── remove the previous managed block ─────────────────────────────────────────
# Anchored at the start of the line (^) so it does not match a mention inside another comment.
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT
awk -v start="$START" -v end="$END" '
	$0 == start  { skipping = 1; next }
	$0 == end    { skipping = 0; next }
	!skipping    { print }
' "$PATCH" >"$TMP"
# strip leftover blank lines at the end
awk 'BEGIN { n = 0 } { lines[NR] = $0 } END {
	while (n < NR && lines[NR - n] ~ /^[[:space:]]*$/) n++
	for (i = 1; i <= NR - n; i++) print lines[i]
}' "$TMP" >"$TMP.clean"
mv "$TMP.clean" "$TMP"

# ── write the new block ───────────────────────────────────────────────────────
{
	echo
	echo "$START"
	echo "#"
	echo "# Generated from the paths of this machine. Run it again after moving"
	echo "# graphify or switching node version — and after any reinstall of the bundle."
	if [ -n "$GRAPHIFY_MCP" ]; then
		cat <<YAML

- id: mcp-graphify
  config:
    serverName: graphify
    transport: stdio
    command: '$GRAPHIFY_MCP'
    args: ['--transport', 'stdio']
    cwd: '$DSH_HOME_DIR'
    toolCallTimeoutMs: 120000
    failOnStartupError: false
YAML
	fi
	if [ -n "$NPX_BIN" ]; then
		cat <<YAML

- id: mcp-lgpd
  config:
    serverName: lgpd
    transport: stdio
    command: '$NPX_BIN'
    args: ['-y', '@lordmendes/lgpd-mcp']
    cwd: '$DSH_HOME_DIR'
    toolCallTimeoutMs: 60000
    failOnStartupError: false
YAML
	fi
	echo "$END"
} >>"$TMP"
mv "$TMP" "$PATCH"
trap - EXIT

echo "==> managed block written to $PATCH"
[ -n "$GRAPHIFY_MCP" ] && echo "    graphify-mcp: $GRAPHIFY_MCP"
[ -n "$NPX_BIN" ] && echo "    npx:          $NPX_BIN"
echo
echo "Restart DSH and check the mcp__graphify__* and mcp__lgpd__* tools."
