#!/usr/bin/env bash
#
# Installs graphify and creates the wrapper that injects the Gemini key.
#
# This is NOT a bundle because it cannot be one: the key is a secret and the wrapper is a
# file local to the machine. A package does not carry a secret, and the bundle would have no way
# of guessing where the graphify binary landed on this machine.
#
# It is idempotent: running it again only rewrites the wrapper. That is precisely what fixes
# the most common case — `uv tool install|upgrade` overwrites the wrapper with a symlink and
# graphify goes back to failing with "No LLM provider configured".
#
# Usage:  ./install/install-graphify.sh
#
set -euo pipefail

GRAPHIFY_VERSION="${GRAPHIFY_VERSION:-0.9.55}"
GRAPHIFY_MODEL="${GRAPHIFY_GEMINI_MODEL:-gemini-flash-latest}"
KEY_FILE="${GRAPHIFY_KEY_FILE:-$HOME/.config/graphify/gemini.key}"
BIN_DIR="$HOME/.local/bin"
DEST="$BIN_DIR/graphify"

if ! command -v uv >/dev/null 2>&1; then
	echo "error: 'uv' not found on PATH. Install uv first." >&2
	exit 1
fi

TOOLS_DIR="$(uv tool dir 2>/dev/null || echo "$HOME/.local/share/uv/tools")"
REAL_BIN="$TOOLS_DIR/graphifyy/bin/graphify"

# ── 1. the package, with every extra it needs ─────────────────────────────────
# `mcp` exposes the MCP server, `gemini` is the CLI's LLM provider, and `sql` brings the SQL
# grammar — without it, `.sql` files contribute nothing to the graph.
# Installing with one extra ERASES the others — that is why they are listed together, always.
echo "==> installing graphifyy[mcp,gemini,sql]==$GRAPHIFY_VERSION"
uv tool install "graphifyy[mcp,gemini,sql]==$GRAPHIFY_VERSION" --force

if [ ! -x "$REAL_BIN" ]; then
	echo "error: expected the binary at $REAL_BIN and it is not there." >&2
	exit 1
fi

# ── 2. the key, outside the repository and outside the wrapper ────────────────
if [ ! -r "$KEY_FILE" ]; then
	mkdir -p "$(dirname "$KEY_FILE")"
	printf 'Paste the Gemini API key (it is stored at %s): ' "$KEY_FILE" >&2
	read -r key
	if [ -z "$key" ]; then
		echo "error: empty key." >&2
		exit 1
	fi
	printf '%s' "$key" >"$KEY_FILE"
	echo "==> key written to $KEY_FILE"
fi
chmod 600 "$KEY_FILE"

# ── 3. the wrapper, with no secret inside ─────────────────────────────────────
# It reads the key at run time. A future `uv tool install` recreates the symlink
# on top of it; running this script again restores the wrapper.
mkdir -p "$BIN_DIR"
rm -f "$DEST"
cat >"$DEST" <<WRAPPER
#!/usr/bin/env bash
# graphify wrapper — generated by dsh-on-fire/install/install-graphify.sh.
# Do not edit by hand: \`uv tool install|upgrade graphifyy\` overwrites this file.
set -euo pipefail

KEY_FILE="\${GRAPHIFY_KEY_FILE:-$KEY_FILE}"

if [ -z "\${GEMINI_API_KEY:-}" ] && [ -r "\$KEY_FILE" ]; then
  GEMINI_API_KEY="\$(cat "\$KEY_FILE")"
  export GEMINI_API_KEY
fi

: "\${GRAPHIFY_GEMINI_MODEL:=$GRAPHIFY_MODEL}"
export GRAPHIFY_GEMINI_MODEL

exec "$REAL_BIN" "\$@"
WRAPPER
chmod 700 "$DEST"

echo "==> wrapper created at $DEST"
echo
echo "done. Check with:"
echo "  graphify --version          # the CLI runs"
echo "  graphify --help             # the commands it actually has"
echo "  tree_sitter_sql available?  # the SQL grammar that the extra installs:"
echo "    $TOOLS_DIR/graphifyy/bin/python -c 'import tree_sitter_sql'"
